### ISSUE TITLE
Enhancing the compression method

### ISSUE THREAD

**Issue by descentis** [descentis/WikECD#7]
Let's say there are N revisions in a doc and we are storing full revisions at multiples of kth indices. Rather than taking the difference between two consecutive revisions that fall under kth and (k+1)th block, we will take the difference each revision and the kth block.

This needs to be tested first, Please add all your code in the experiment section only.
A theoretical analysis of this has to be performed

**Comment by hershd23** [comment]
Okay so for any revision we would need to fetch the complete revision at the nearest multiple of k and then save one diff from k to (k+a)th revision. Got it.

Also can you direct me to some working code where you are doing current (consecutive) format of revisions.

**Comment by descentis** [comment]
https://github.com/descentis/WikECD/blob/5bca0965c6f639c9e452146bf100d82c2dd10d56/wikecd/retrieval.py#L256

Please check the referenced code
